### ISSUE TITLE
다음주 까지 할일 (5.14)

### ISSUE THREAD

**Issue by JunsuLime** [HyOsori/Crawler#1]
편의를 위해 언어 버전은 python 3.5 이상으로 맞추겠습니다.

다음주 (5.22) 까지 해야할 일은

Crawler 의 선정입니다. 각각 크롤러마다 특정이 있고 장단점이 있을텐데요. 각자 여러 자료를 찾아봐서 어떤 크롤러가 좋을 지 생각해보고 자신의 의견을 피력해 상대방을 설득시켜주세요 ㅇㅂㅇ

https://elitedatascience.com/python-web-scraping-libraries

위의 링크는 파이썬에 있는 여러 크롤러에 관한 글입니다. 이 외에도 많은 글이 있으니 읽어보시고 댓글로 어떤 것을 쓰고 싶은지 왜 쓰고 싶은지 계속 줄줄이 달아주세요.
 그래서 다음주 5.22 안으로 어떤 크롤러를 쓸지 두분께서 정해요 ㅎㅎㅎㅎ

**Comment by JunsuLime** [comment]
예시1)

AAA 라는 Crawler 를 쓰고 싶어요. 문서화가 깔끔하게 잘 되어있고 참고할 자료도 많아서 쓰기 편해요 ㅎㅎ

**Comment by JunsuLime** [comment]
예시2)

AAA 는 속도도 너무 느리고 불안정 하다는 단점이 있어요. 그런점에서 BBB 를 쓰는 것이 좋을 것 같아요. BBB 또한 문서화도 잘 되어있고, [링크](https://github.com/HyOsori)를 보면 성능도 훨씬 좋은 것을 알 수 있어요 ㅇㅂㅇ

**Comment by JunsuLime** [comment]
BeautifulSoup 의 장점

python crawler 라는 문구로 검색을 했을 경우 BeautifulSoup library 로 한 경우가 가장 많이 검색됩니다.

https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 문서화도 잘 되어 있고

사용해본 결과 Python 기본 자료구조 dict 과 list 의 사용법과 유사해서 처음 사용하는 사람도 어렵지않게 쓸수 있습니당 ~_~

또한 BeautifulSoup 는 htmlParser 기능만 제공하기 때문에 쓰고 싶은 http library 를 쓸 수 있는 장점이 있습니다

다른 의견 있으면 제시해주세요 ㅎㅎㅎㅎ

**Comment by yutaejeong** [comment]
웹 페이지와 상호작용을 할 수 있는 점에서 Selenium이 좋다고 생각합니다. 로그인이 필요한 페이지도 로그인을 통해 가져올 수도 있고, 버튼 클릭과 같은 상호작용이 가능합니다. Selenium은 WebDriver를 필요로 합니다. Chrome, Firefox 등에서 제공하는 웹 드라이버 파일을 받아서 사용합니다. 그래서 실제로 브라우저가 실행되는 방식으로 작동합니다. 브라우저 창을 숨길 수는 있지만, 같이 뜨는 콘솔창은 어떻게 끄는지 모르겠습니다.

BeautifulSoup는 받아온 html에서 각각의 태그를 하나의 타입처럼 다룰 수 있는 것같아 편해보입니다. 특히, BeautifulSoup가 단독으로 쓰이기보다 requests+BeautifulSoup, selenium+BeautifulSoup처럼 다른 크롤링 라이브러리와 같이 쓰이더라고요. 그런데, Selenium에서도 element의 text를 가져오는 등 BeautifulSoup처럼 편하게 쓸 수 있는 것 같더라고요. 

만약, 가져올 페이지가 로그인과 같은 상호작용이 필요하지 않은 페이지인 경우에는 굳이 Selenium을 사용하는 것보다 requests+BeatifulSoup의 조합으로 가는 것이 보편적인 것 같습니다. requests는많은 기능보다는 parameter를 전송하거나, text-encoding 설정 등 최소한의 기능만을 제공하는 것 같습니다. 그래서 익히기에도 쉬워보입니다.

결론은, 로그인처럼 상호작용이 있어야만 접근 가능한 페이지에는 Selenium을, 별다른 조작 없이 바로 보여지는 페이지에는 Requsts+BeautifulSoup를 사용하는 것이 좋을 것이라고 생각합니다.
